#include "test.hpp"

TEST_CASE("TTac edge and corner check", "[ttac]") {
  SECTION("Edges") {
    REQUIRE_EDGE(TTAC_TOP);
    REQUIRE_EDGE(TTAC_BOTTOM);
    REQUIRE_EDGE(TTAC_LEFT);
    REQUIRE_EDGE(TTAC_RIGHT);

    REQUIRE_EDGE_FALSE(TTAC_TOP_LEFT);
    REQUIRE_EDGE_FALSE(TTAC_TOP_RIGHT);
    REQUIRE_EDGE_FALSE(TTAC_BOTTOM_LEFT);
    REQUIRE_EDGE_FALSE(TTAC_BOTTOM_RIGHT);
  }

  SECTION("Corners") {
    REQUIRE_CORNER(TTAC_TOP_LEFT);
    REQUIRE_CORNER(TTAC_TOP_RIGHT);
    REQUIRE_CORNER(TTAC_BOTTOM_LEFT);
    REQUIRE_CORNER(TTAC_BOTTOM_RIGHT);

    REQUIRE_CORNER_FALSE(TTAC_TOP);
    REQUIRE_CORNER_FALSE(TTAC_BOTTOM);
    REQUIRE_CORNER_FALSE(TTAC_LEFT);
    REQUIRE_CORNER_FALSE(TTAC_RIGHT);
  }
}
