name: Build Raylib Example

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      LINK_FLAGS: ${{ matrix.os == 'windows-latest' && '-static' || '' }}

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwayland-dev libxkbcommon-dev xorg-dev xvfb

    - name: Configure CMake
      shell: bash
      run: cmake --preset release -G Ninja -D TTAC_EXAMPLE=ON -DCMAKE_EXE_LINKER_FLAGS="$LINK_FLAGS" 

    - name: Build
      run: cmake --build --preset release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ttac_raylib-${{ matrix.os }}
        path: ./bin/ttac_raylib*
