name: Build Raylib Example

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      shell: bash
      run: |
        LINK_FLAGS=""
        if [[ "${RUNNER_OS}" != "macOS" ]]; then
          LINK_FLAGS="-static"
        fi
        cmake --preset release -G Ninja -D TTAC_EXAMPLE=ON -DCMAKE_EXE_LINKER_FLAGS="$LINK_FLAGS"

    - name: Build
      run: cmake --build --preset release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ttac_raylib-${{ matrix.os }}
        path: ./bin/ttac_raylib*
