name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest   # no matrix needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set CPM_SOURCE_CACHE
        shell: bash
        run: |
          echo "CPM_SOURCE_CACHE=${{ github.workspace }}/.cpm_cache" >> $GITHUB_ENV

      - name: Restore CPM cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CPM_SOURCE_CACHE }}
          key: ${{ runner.os }}-cpm-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cpm-

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          remove_stale_cache: false

      - name: Configure with CMake
        run: |
          cmake -B build \
                -DTTAC_TESTS=ON \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_C_LAUNCHER=ccache \
                -DCMAKE_CXX_LAUNCHER=ccache

      - name: Build
        run: cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
