name: Build and Deploy to GitHub Pages

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ----- Checkout repository -----
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----- CPM cache -----
      - name: Set CPM_SOURCE_CACHE
        shell: bash
        run: |
          echo "CPM_SOURCE_CACHE=${{ github.workspace }}/.cpm_cache" >> $GITHUB_ENV

      - name: Restore CPM cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CPM_SOURCE_CACHE }}
          key: ${{ runner.os }}-cpm-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cpm-

      # ----- Setup ccache -----
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          remove_stale_cache: false

      # ----- Setup Emscripten -----
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          actions-cache-folder: 'emsdk-cache'

      # ----- Configure CMake -----
      - name: Configure with CMake (Web)
        run: emcmake cmake --preset web -G Ninja

      # ----- Build -----
      - name: Build Web
        run: cmake --build --preset web --target ttac_raylib

      # ----- List output for debugging -----
      - name: List web folder
        run: ls -R web

      # ----- Upload artifact to GitHub Pages -----
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
